# Generated by Django 5.1.5 on 2025-02-10 18:55

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='username',
            field=models.CharField(blank=True, db_index=True, max_length=20, unique=True, validators=[django.core.validators.MinLengthValidator(6)]),
        ),
    ]
